[package]
name = "aircraft_config"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
config.workspace = true
dotenvy.workspace = true
serde.workspace = true
thiserror.workspace = true