[package]
name = "aircraft_observability"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
# System Diagnostics & Error Utilities
anyhow.workspace = true
thiserror.workspace = true

# Tracing Architecture & JSON Formatters
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
